apiVersion: v1
kind: ConfigMap
metadata:
  name: credential-manager-config
  namespace: vcenter-provisioner
data:
  PORT: "8090"
  CORS_ORIGINS: "http://localhost:5173,http://provisioner-ui,https://vc-ui.playground.net"
