apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-config.yaml
  - auth-service-config.yaml
  - credential-manager-config.yaml
  - monitoring-service-config.yaml
  - provisioner-ui-config.yaml
  - stats-service-config.yaml
  - typing-service-config.yaml
  - vcenter-operations-config.yaml
  - vcenter-provisioner-config.yaml
  - vm-orchestrator-config.yaml
