apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioner-ui-config
  namespace: vcenter-provisioner
data:
  VITE_API_URL: "/api"
  CORS_ORIGINS: "http://localhost:5173,http://provisioner-ui,https://vc-ui.playground.net"
  PROBE_INTERVAL: "300"
  PROBE_MODE: "sample"
  PROBE_SAMPLE_COUNT: "3"
  PROBE_TARGETS: "api-gateway,auth-service,monitoring-service"
