apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: vcenter-provisioner
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
      name: http
