apiVersion: v1
kind: Service
metadata:
  name: stats-service
  namespace: vcenter-provisioner
  labels:
    app: stats-service
spec:
  type: ClusterIP
  selector:
    app: stats-service
  ports:
    - port: 8001
      targetPort: 8001
      name: http
