apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
  namespace: coroot
spec:
  metricsRefreshInterval: 15s
  authAnonymousRole: ~
  authBootstrapAdminPassword: "CambiaEstePassword123!"
  
  storage:
    size: 20Gi
    className: tanzu-storage
    reclaimPolicy: Retain
  
  clickhouse:
    shards: 2
    replicas: 2
    storage:
      size: 50Gi
  
  service:
    type: ClusterIP
    port: 8080
  
  ingress:
    className: contour
    host: coroot.playground.net
    path: /
    tls:
      hosts:
        - coroot.playground.net
      secretName: coroot-playground-tls
  
  apiKeySecret:
    name: coroot
    key: agent-api-key
  projects:
    - name: production
      apiKeys:
        - description: Clave API para agentes de Coroot
          keySecret:
            name: coroot
            key: agent-api-key
