apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coroot-playground-tls
  namespace: coroot
spec:
  secretName: coroot-playground-tls
  commonName: coroot.playground.net
  dnsNames:
    - coroot.playground.net
  issuerRef:
    name: coroot-ca-issuer
    kind: ClusterIssuer
