apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: vcenter-provisioner-dev
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: curl
      image: curlimages/curl
      command: ["sh", "-c", "curl -vvv -k -m 30 https://vc-ui. playground. net/ auth/ login -X POST -H Content-Type: application/ json -d '{\"username\":\"admin\",\"password\":\"password123\"}'"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      imagePullPolicy: Always