apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vcenter-provisioner
  namespace: vcenter-provisioner-dev
spec:
  virtualhost:
    fqdn: vc-ui.playground.net
    tls:
      secretName: vc-ui-tls
  routes:
    - conditions:
        - prefix: /auth
      services:
        - name: api-gateway
          port: 3000
    - conditions:
        - prefix: /api
      pathRewritePolicy:
        replacePrefix:
          - prefix: /api
            replacement: /
      services:
        - name: api-gateway
          port: 3000
    - conditions:
        - prefix: /
      services:
        - name: provisioner-ui
          port: 80
