apiVersion: v1
kind: Service
metadata:
  name: credential-manager
  namespace: vcenter-provisioner
  labels:
    app: credential-manager
spec:
  type: ClusterIP
  selector:
    app: credential-manager
  ports:
    - port: 8090
      targetPort: 8090
      name: http
