apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  - clusterissuer-selfsigned.yaml
  - certificate-ca.yaml
  - vcenter-ca-issuer.yaml
  - vc-ui-tls-certificate.yaml
