apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vc-ui-tls
  namespace: vcenter-provisioner
spec:
  secretName: vc-ui-tls
  dnsNames:
    - vc-ui.playground.net
  issuerRef:
    name: vcenter-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
