apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-hpa.yaml
  - auth-service-hpa.yaml
  - credential-manager-hpa.yaml
  - monitoring-service-hpa.yaml
  - provisioner-ui-hpa.yaml
  - stats-service-hpa.yaml
  - typing-service-hpa.yaml
  - vcenter-operations-hpa.yaml
  - vm-orchestrator-hpa.yaml
