exports.up = (pgm) => {
  // provision_logs y custom_charts ahora se crean en 1773800000012_referential_integrity.
  // Esta migración persiste como no-op para no romper DBs que ya la tengan en pgmigrations.
  // Los CREATE TABLE IF NOT EXISTS e índices son idempotentes (no-op si ya existen).
  pgm.sql(`CREATE TABLE IF NOT EXISTS provision_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      job_id VARCHAR(100) NOT NULL UNIQUE,
      vm_name VARCHAR(255) NOT NULL,
      status VARCHAR(50) NOT NULL,
      vm_class_id INTEGER,
      vm_class_name VARCHAR(100),
      vcenter_id INTEGER,
      vcenter_name VARCHAR(255),
      error_reason VARCHAR(500),
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
      updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now())`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_provision_logs_status ON provision_logs (status)`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_provision_logs_created_at ON provision_logs (created_at)`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_provision_logs_vm_class ON provision_logs (vm_class_id)`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_provision_logs_vcenter ON provision_logs (vcenter_id)`);

  pgm.sql(`CREATE TABLE IF NOT EXISTS custom_charts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL,
      name VARCHAR(100) NOT NULL,
      chart_type VARCHAR(50) NOT NULL,
      metric VARCHAR(100) NOT NULL,
      group_by VARCHAR(100),
      timeframe VARCHAR(50) NOT NULL DEFAULT '7d',
      filters JSONB,
      is_public BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
      updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now())`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_custom_charts_user ON custom_charts (user_id)`);
};

exports.down = (pgm) => {
  pgm.sql(`DROP TABLE IF EXISTS provision_logs CASCADE`);
  pgm.sql(`DROP TABLE IF EXISTS custom_charts CASCADE`);
};
