exports.up = (pgm) => {
  // =============================================================================
  // 2.1: SERIAL → GENERATED BY DEFAULT AS IDENTITY (11 tablas)
  // =============================================================================
  // Cada tabla SERIAL tiene id INTEGER DEFAULT nextval('tabla_col_seq')
  // Migramos: DROP DEFAULT + ADD GENERATED BY DEFAULT AS IDENTITY + DROP old sequence

  const serialTables = [
    'users',
    'vcenter_connections',
    'vcenter_credentials_audit',
    'vm_classes',
    'typification_templates',
    'vm_provisions',
    'audit_logs',
    'provision_logs',
    'custom_charts',
    'monitoring.probes',
    'monitoring.connectivity_matrix',
  ];

  for (const tbl of serialTables) {
    pgm.sql(`
      DO $$ BEGIN
        ALTER TABLE ${tbl} ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE ${tbl} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
      EXCEPTION
        WHEN others THEN NULL;
      END $$;
    `);
  }

  // =============================================================================
  // 2.2: TIMESTAMP → TIMESTAMP WITH TIME ZONE (10 tablas, ~22 columnas)
  // =============================================================================
  // USING col AT TIME ZONE 'UTC' — garantiza interpretación correcta de datos existentes
  // Previene data corruption (ver Context7 docs)

  pgm.sql(`SET timezone = 'UTC'`);

  const tsColumns = [
    { table: 'users', cols: ['created_at', 'updated_at'] },
    { table: 'vcenter_connections', cols: ['created_at', 'updated_at'] },
    { table: 'vcenter_credentials_audit', cols: ['performed_at'] },
    { table: 'typification_templates', cols: ['created_at', 'updated_at'] },
    { table: 'typification_counters', cols: ['updated_at'] },
    { table: 'vm_classes', cols: ['created_at', 'updated_at'] },
    { table: 'vm_provisions', cols: ['created_at', 'updated_at'] },
    { table: 'audit_logs', cols: ['created_at'] },
    { table: 'provision_logs', cols: ['created_at', 'updated_at'] },
    { table: 'custom_charts', cols: ['created_at', 'updated_at'] },
  ];

  for (const { table, cols } of tsColumns) {
    for (const col of cols) {
      pgm.sql(`
        ALTER TABLE ${table}
          ALTER COLUMN ${col} TYPE TIMESTAMP WITH TIME ZONE
            USING ${col} AT TIME ZONE 'UTC';
      `);
    }
  }

  // =============================================================================
  // 2.5: custom_charts.filters JSON → JSONB
  // =============================================================================
  pgm.sql(`
    ALTER TABLE custom_charts
      ALTER COLUMN filters TYPE JSONB;
  `);
};

exports.down = (pgm) => {
  // Revertir 2.5: JSONB → JSON
  pgm.sql(`
    ALTER TABLE custom_charts
      ALTER COLUMN filters TYPE JSON;
  `);

  // Revertir 2.2: TIMESTAMPTZ → TIMESTAMP
  pgm.sql(`SET timezone = 'UTC'`);

  const tsColumns = [
    { table: 'users', cols: ['created_at', 'updated_at'] },
    { table: 'vcenter_connections', cols: ['created_at', 'updated_at'] },
    { table: 'vcenter_credentials_audit', cols: ['performed_at'] },
    { table: 'typification_templates', cols: ['created_at', 'updated_at'] },
    { table: 'typification_counters', cols: ['updated_at'] },
    { table: 'vm_classes', cols: ['created_at', 'updated_at'] },
    { table: 'vm_provisions', cols: ['created_at', 'updated_at'] },
    { table: 'audit_logs', cols: ['created_at'] },
    { table: 'provision_logs', cols: ['created_at', 'updated_at'] },
    { table: 'custom_charts', cols: ['created_at', 'updated_at'] },
  ];

  for (const { table, cols } of tsColumns) {
    for (const col of cols) {
      pgm.sql(`
        ALTER TABLE ${table}
          ALTER COLUMN ${col} TYPE TIMESTAMP WITHOUT TIME ZONE
            USING ${col} AT TIME ZONE 'UTC';
      `);
    }
  }

  // Revertir 2.1: IDENTITY → SERIAL
  // DROP IDENTITY + recrear DEFAULT nextval(sequence)
  const serialTables = [
    'users',
    'vcenter_connections',
    'vcenter_credentials_audit',
    'vm_classes',
    'typification_templates',
    'vm_provisions',
    'audit_logs',
    'provision_logs',
    'custom_charts',
    'monitoring.probes',
    'monitoring.connectivity_matrix',
  ];

  for (const tbl of serialTables) {
    pgm.sql(`
      DO $$ BEGIN
        ALTER TABLE ${tbl} ALTER COLUMN id DROP IDENTITY;
      EXCEPTION
        WHEN others THEN NULL;
      END $$;
    `);
  }
};
