apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - restrict-monitoring-ingress.yaml
  - restrict-stats-ingress.yaml
  - restrict-credential-manager-ingress.yaml
  - restrict-postgres-ingress.yaml
