apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-stats-ingress
  namespace: vcenter-provisioner
spec:
  podSelector:
    matchLabels:
      app: stats-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - port: 8001
          protocol: TCP
