apiVersion: v1
kind: Service
metadata:
  name: backup-service
  namespace: default
spec:
  selector:
    app: backup-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
