apiVersion: v1
kind: Service
metadata:
  name: backup-service
  namespace: vcenter-provisioner
  labels:
    app: backup-service
spec:
  type: ClusterIP
  selector:
    app: backup-service
  ports:
    - port: 8002
      targetPort: 8002
      name: http
