apiVersion: v1
kind: Service
metadata:
  name: typing-service
  namespace: vcenter-provisioner
  labels:
    app: typing-service
spec:
  type: ClusterIP
  selector:
    app: typing-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
