apiVersion: batch/v1
kind: Job
metadata:
  name: vcenter-provisioner-migrations
  namespace: vcenter-provisioner
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: auth-service
        job: migrations
    spec:
      containers:
      - name: migrations
        image: harbor.playground.net/ms/vcenter-provisioner-migrations:v2
        imagePullPolicy: Always
        command: ["npx", "node-pg-migrate", "up"]
        envFrom:
        - secretRef:
            name: vcenter-provisioner-secrets
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: OnFailure
