apiVersion: v1
kind: Service
metadata:
  name: provisioner-ui
  namespace: vcenter-provisioner
  labels:
    app: provisioner-ui
spec:
  type: ClusterIP
  selector:
    app: provisioner-ui
  ports:
    - port: 80
      targetPort: 80
      name: http
