apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        envFrom:
        - secretRef:
            name: shared-secrets
        - configMapRef:
            name: api-gateway-config
        - secretRef:
            name: vcenter-provisioner-secrets
