apiVersion: v1
kind: Secret
metadata:
  name: credential-manager-secrets
type: Opaque
stringData:
  DB_URL: "postgresql://app_user:password123@pgbouncer:6432/vcenter_provisioner"
  VCENTER_MASTER_KEY: "dhnJ0KJWYUupFZgBAwZRY0HLCwnfQq7WK3y7HQnIirk="
