apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          args:
            - postgres
            - -c
            - shared_buffers=1GB
            - -c
            - effective_cache_size=3GB
            - -c
            - random_page_cost=1.1
            - -c
            - effective_io_concurrency=200
            - -c
            - work_mem=32MB
            - -c
            - maintenance_work_mem=256MB
            - -c
            - wal_buffers=16MB
            - -c
            - min_wal_size=1GB
            - -c
            - max_wal_size=4GB
            - -c
            - max_connections=50
            - -c
            - log_min_duration_statement=1000
            - -c
            - wal_level=replica
