apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          startupProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 30
            periodSeconds: 10
