apiVersion: v1
kind: Secret
metadata:
  name: credential-manager-secrets
  namespace: vcenter-provisioner
type: Opaque
data:
  DB_URL: cG9zdGdyZXNxbDovL2FudGlncmF2aXR5OnBhc3N3b3JkMTIzQGRiOjU0MzIvdmnlbnRlcl9wcm92aXNpb25lcg==
