apiVersion: v1
kind: Secret
metadata:
  name: credential-manager-secrets
  namespace: vcenter-provisioner
type: Opaque
data:
  DB_URL: cG9zdGdyZXNxbDovL2FudGlncmF2aXR5OnBhc3N3b3JkMTIzQHBvc3RncmVzOjU0MzIvYW50aWdyYXZpdHk=
  VCENTER_MASTER_KEY: ZGhuSjBLSldZVXVwRlpnQkF3WlJZMEhMQ3duZlFxN1dLM3k3SFFuSWlyaz0=
