apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-service-secrets.yaml
  - credential-manager-secrets.yaml
  - monitoring-service-secrets.yaml
  - stats-service-secrets.yaml
  - typing-service-secrets.yaml
  - vcenter-operations-secrets.yaml
  - vcenter-provisioner-secrets.yaml
  - vm-orchestrator-secrets.yaml
